administration_Module:
    path:     /
    defaults: { _controller: "BackendBundle:Module:index" }

administration_Module_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Module:show" }

administration_Module_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Module:new" }

administration_Module_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Module:create" }
    methods:  POST

administration_Module_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Module:edit" }

administration_Module_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Module:update" }
    methods:  [POST, PUT]

administration_Module_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Module:delete" }
    methods:  [POST, DELETE]
